// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxHkmGRh8SFvqXYG6aJVx860N1GG5Mibw',
    appId: '1:940026695087:web:0ed2839673318368ccf35a',
    messagingSenderId: '940026695087',
    projectId: 'auth-70611',
    authDomain: 'auth-70611.firebaseapp.com',
    storageBucket: 'auth-70611.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWK84QnvAuKFtfnIEqxtCK3p4t2OWRKXM',
    appId: '1:940026695087:android:3674b6226f28ddfeccf35a',
    messagingSenderId: '940026695087',
    projectId: 'auth-70611',
    storageBucket: 'auth-70611.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKrm6B_UmM33cMKxPsAkuIWF-7JxMt1hI',
    appId: '1:940026695087:ios:e1803c953907a909ccf35a',
    messagingSenderId: '940026695087',
    projectId: 'auth-70611',
    storageBucket: 'auth-70611.firebasestorage.app',
    iosBundleId: 'com.example.apkAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKrm6B_UmM33cMKxPsAkuIWF-7JxMt1hI',
    appId: '1:940026695087:ios:e1803c953907a909ccf35a',
    messagingSenderId: '940026695087',
    projectId: 'auth-70611',
    storageBucket: 'auth-70611.firebasestorage.app',
    iosBundleId: 'com.example.apkAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxHkmGRh8SFvqXYG6aJVx860N1GG5Mibw',
    appId: '1:940026695087:web:8dc8215acf0f9621ccf35a',
    messagingSenderId: '940026695087',
    projectId: 'auth-70611',
    authDomain: 'auth-70611.firebaseapp.com',
    storageBucket: 'auth-70611.firebasestorage.app',
  );
}
