// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCchBDtdXUlRkcENxZhDHJ_x-j3UCblsZQ',
    appId: '1:495280896717:web:fbb84c4b7e57675a4cc784',
    messagingSenderId: '495280896717',
    projectId: 'notes-45cb0',
    authDomain: 'notes-45cb0.firebaseapp.com',
    storageBucket: 'notes-45cb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgJJBUfFmc3vAVB8HK-YtEVjh7DRsnSfQ',
    appId: '1:495280896717:android:a39fd671d0a477924cc784',
    messagingSenderId: '495280896717',
    projectId: 'notes-45cb0',
    storageBucket: 'notes-45cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBePMEtZsWy_IqmUUa8W_52IimcynSCmDI',
    appId: '1:495280896717:ios:671da373bec9d3b74cc784',
    messagingSenderId: '495280896717',
    projectId: 'notes-45cb0',
    storageBucket: 'notes-45cb0.firebasestorage.app',
    iosBundleId: 'com.example.notesTa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBePMEtZsWy_IqmUUa8W_52IimcynSCmDI',
    appId: '1:495280896717:ios:671da373bec9d3b74cc784',
    messagingSenderId: '495280896717',
    projectId: 'notes-45cb0',
    storageBucket: 'notes-45cb0.firebasestorage.app',
    iosBundleId: 'com.example.notesTa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCchBDtdXUlRkcENxZhDHJ_x-j3UCblsZQ',
    appId: '1:495280896717:web:e00a378ca698ad514cc784',
    messagingSenderId: '495280896717',
    projectId: 'notes-45cb0',
    authDomain: 'notes-45cb0.firebaseapp.com',
    storageBucket: 'notes-45cb0.firebasestorage.app',
  );
}
